---
- name: Download base image
  get_url:
    url: "{{ base_image_url }}"
    dest: "/tmp/{{ base_image_name }}"
    checksum: "sha512:{{ base_image_sha }}"
- name: Copy base image to libvirt directory
  copy:
    dest: "{{ libvirt_pool_dir }}/{{ item.hostname }}.qcow2"
    src: "/tmp/{{ base_image_name }}"
    force: no
    remote_src: yes
    mode: 0600
    owner: libvirt-qemu
    group: libvirt-qemu
  become: yes
  register: copy_results
- name: Configure the image
  command: |
    virt-customize -a {{ libvirt_pool_dir }}/{{ item.hostname }}.qcow2 \
    --hostname {{ item.hostname }} \
    --firstboot-install kbd,htop \
    --firstboot roles/kvm_provision/files/setup.sh \
    --root-password password:{{ vm_root_pass }} \
    --copy-in roles/kvm_provision/files/keyboard:/etc/default/ \
    --copy-in roles/kvm_provision/files/josef:/etc/sudoers.d/ \
    --copy-in /home/josef/.ssh/homelab-{{ item.hostname }}.pub:/etc/ \
    --chown 0:0:/etc/sudoers.d/josef \
    --copy-in roles/kvm_provision/files/enp1s0.network:/etc/systemd/network/ \
    --ssh-inject 'root:file:{{ ssh_key }}'
  become: yes
  when: copy_results is changed
- name: Define VM
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'vm-template.xml.j2') }}"
  become: yes
  when: "item.hostname not in existing_vms.list_vms"
- name: Ensure VM is started
  community.libvirt.virt:
    name: "{{ item.hostname }}"
    state: running
  register: vm_start_results
  until: "vm_start_results is success"
  retries: 15
  delay: 2
  become: yes
- name: Ensure temporary file is deleted
  file:
    path: "/tmp/{{ base_image_name }}"
    state: absent
  when: cleanup_tmp | bool
- name: Pause for 30 seconds for the {{ item.hostname }} network to come up
  ansible.builtin.pause:
    seconds: 30
- name: Get IP of the VM {{ item.hostname }}
  become: yes
  shell: >
    arp -e | grep -i `virsh -q domiflist {{ item.hostname }} | awk '{ print $5 }'` | awk '{ print $1 }'
  register: vm_ip
- name: set up DNS alias for {{ item.hostname }}
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ vm_ip.stdout_lines[0] }} {{ item.hostname }}.example.local"
