---
# tasks file for kvm_provision
- name: Ensure requirements in place
  package:
    name:
      - guestfs-tools
      - python3-libvirt
      - net-tools
    state: present
  become: yes
- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: no
  become: yes
- name: Create VM if not exists
  block:
    - name: Set up the ssh certificates
      ansible.builtin.include_tasks: set_up_ssh_certs.yaml
      loop: "{{ machines }}"
    - name: Run the create vms tasks file
      ansible.builtin.include_tasks: create_vm.yaml
      loop: "{{ machines }}"
    - name: create ssh config fragment
      ansible.builtin.template:
        src: ssh-config
        dest: "~/.ssh/homelab.config"
        mode: "0600"
    - name: refer to the ssh config fragment from the main ssh config file
      ansible.builtin.lineinfile:
        path: "~/.ssh/config"
        line: Include homelab.config
        state: present
        mode: "0600"
