---
# tasks file for kvm_provision
- name: Ensure requirements in place
  package:
    name:
      - guestfs-tools
      - python3-libvirt
    state: present
  become: yes
- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: no
  become: yes
- name: Create VM if not exists
  block:
    - name: Run the create vms tasks file
      ansible.builtin.include_tasks: create_vm.yaml
      loop:
        - hostname: cp-0
          vm_ram_mb: 4096
          vm_vcpus: 2
        - hostname: worker-00
          vm_ram_mb: 2048
          vm_vcpus: 1
