---
# defaults file for kvm_provision
base_image_name: debian-13-generic-amd64.qcow2
base_image_url: https://cloud.debian.org/images/cloud/trixie/latest/{{ base_image_name }}
base_image_sha: 4c85760a0b1e8f0dbdc19d632775d5a6333bda2b79ae1b89cc72d0c4a791f98cbb6413ea1aee2253df18515cba1c94ae60d3794cf02ce33adf5ceddbd05caff8
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_name: debian-trixie
vm_vcpus: 2
vm_ram_mb: 2048
vm_net: default
vm_root_pass: test123
cleanup_tmp: no
ssh_key: /root/.ssh/id_rsa.pub
